import express from 'express';
import { getUserProfile, loginUser, myProfile, updateProfilePic, UpdateUser } from '../controller/user.js';
import { isAuth } from '../middleware/isAuth.js';
import upload from '../middleware/multer.js';
const router =express.Router();
router.post("/login",loginUser);    
router.get("/me",isAuth,myProfile);
router.get("/user/:id",getUserProfile);
router.post("/user/update",isAuth,UpdateUser);
router.post("/user/update/pic",isAuth,upload,updateProfilePic);
export default router;